# Generated by Django 4.2.5 on 2023-10-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tackle", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("unsold", "Unsold"), ("sold", "Sold")],
                default="unsold",
                max_length=10,
            ),
        ),
    ]
