# Generated by Django 4.2.5 on 2023-10-02 11:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tackle", "0003_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
