# Generated by Django 4.2.5 on 2023-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tackle", "0004_product_shipping"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="status",
            new_name="financial_status",
        ),
        migrations.AddField(
            model_name="product",
            name="visibility",
            field=models.CharField(
                choices=[("draft", "Draft"), ("live", "Live")],
                default="draft",
                max_length=5,
            ),
        ),
    ]
