# Generated by Django 4.2.5 on 2023-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tackle", "0005_rename_status_product_financial_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.TextField()),
                ("header", models.CharField(max_length=255)),
                ("status", models.CharField(default="received", max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
