# Generated by Django 4.2.5 on 2023-10-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_alter_order_user"),
        ("tackle", "0006_webhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooklog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth_app.order",
            ),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
