# Generated by Django 4.2.5 on 2023-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tackle", "0007_webhooklog_order_webhooklog_payment_intent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product-images/2023/10/"),
        ),
    ]
