# Generated by Django 4.2.5 on 2023-09-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mangopay_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mangopay_user_type",
                    models.CharField(
                        blank=True,
                        choices=[("NATURAL", "Natural"), ("LEGAL", "Legal")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mangopay_wallet_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("kyc_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bank_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "legal_rep_first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "legal_rep_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.customuser",
                    ),
                ),
            ],
        ),
    ]
