# Generated by Django 4.2.5 on 2023-09-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="MangoPay",
        ),
    ]
