# Generated by Django 4.2.5 on 2023-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="MangoPay",
        ),
    ]
