# Generated by Django 4.2.5 on 2023-10-11 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
