# Generated by Django 4.2.5 on 2023-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0010_customuser_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_stripe_verified",
            field=models.BooleanField(default=False),
        ),
    ]
