# Generated by Django 4.2.5 on 2023-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0012_order_tracking_company_order_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
